# Project information
site_name: team-re-boot
site_url: https://team-re-boot.github.io/team-re-boot
site_author: Masaya Kataoka
site_description: ''
copyright: Copyright &copy; 2023 - Masaya Kataoka

# Repository
repo_name: team-re-boot/team-re-boot
repo_url: https://github.com/team-re-boot/team-re-boot
edit_uri: ''
docs_dir: docs

theme:
  name: material
  language: en
  features:
    - navigation.tabs
    - navigation.expand
    - navigation.top
    - toc.integrate
    #- header.autohide
  palette:
    scheme: default
  font:
    text: Roboto
    code: Roboto Mono
  icon:
    logo: fontawesome/solid/robot
    repo: fontawesome/brands/github

# Plugins
plugins:
  - git-revision-date-localized
  - gitsnippet
  - search
  - mermaid2:
      arguments:
        theme: base
        themeVariables:
          fontFamily: verdana
          fontSize: 12px
          darkMode: false
          background: "#fff"
          primaryColor: "#DEDFEF"
          #secondaryColor: "#000"
          #mainBkg: "#0000"  # affect node bkg
          nodeBorder: "#000"
          clusterBkg: "#fff"
          clusterBorder: "#000"
          #titleColor: "#808080"
          edgeLabelBackground: "#eee"
        logLevel: 5
        securityLevel: loose
        startOnLoad: true
        arrowMarkerAbsolute: false
        flowchart:
          diagramPadding: 8
          nodeSpacing: 50
          rankSpacing: 50
          useMaxWidth: false

# Customization
extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/hakuturu583
    - icon: fontawesome/solid/paper-plane
      link: mailto:<ms.kataoka@gmail.com>

extra_css:
  - https://use.fontawesome.com/releases/v5.15.0/css/all.css

extra_javascript:
  - https://unpkg.com/mermaid/dist/mermaid.min.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.1.1/highlight.min.js

# Extensions
markdown_extensions:
  - admonition
  - attr_list
  - codehilite: { guess_lang: false }
  - fontawesome_markdown
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.emoji
  - pymdownx.highlight
  - toc: { permalink: "#" }
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_div_format

nav:
  - Home: index.md
  - Meeting Minutes:
      "2022-06-03": minutes/2023-06-03.md